# Generated by Django 4.2.13 on 2024-10-07 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesik_Admin",
            fields=[
                (
                    "admin_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="관리자 고유 ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=70,
                        null=True,
                        unique=True,
                        verbose_name="관리자 로그인 ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=100, null=True, verbose_name="관리자 로그인 PW"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="관리자 이름")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="관리자 이메일"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
            ],
            options={
                "db_table": "admin",
            },
        ),
    ]
