# Generated by Django 4.2.14 on 2024-08-18 20:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trainer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="등록 고객 고유 ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="고객명")),
                ("contact", models.IntegerField(verbose_name="연락처")),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "남"), (1, "여")], null=True, verbose_name="성별"
                    ),
                ),
                ("birth", models.DateField(verbose_name="생년월일")),
                ("height", models.IntegerField(null=True, verbose_name="신장")),
                ("weight", models.IntegerField(verbose_name="체중")),
                (
                    "activity",
                    models.IntegerField(
                        choices=[
                            (0, "정적 (운동을 거의 하지 않음)"),
                            (1, "가벼운 활동 (주 1~2일 운동)"),
                            (2, "적당히 활동적 (주 3~5일 운동)"),
                            (3, "매우 활동적 (주 6~7일 운동)"),
                            (4, "선수 (매일 2회 이상 운동)"),
                        ],
                        null=True,
                        verbose_name="활동량",
                    ),
                ),
                (
                    "goal",
                    models.IntegerField(
                        choices=[
                            (0, "급격한 체중 감량 (~1kg/주)"),
                            (1, "적당한 체중 감량 (~0.5kg/주)"),
                            (2, "천천한 체중 감량 (~0.25kg/주)"),
                            (3, "체중 유지"),
                            (4, "천천한 체중 증량 (~0.25kg/주)"),
                            (5, "적당한 체중 증량 (~0.5kg/주)"),
                            (6, "빠른 체중 증량 (~1kg/주)"),
                        ],
                        null=True,
                        verbose_name="운동 목표",
                    ),
                ),
                ("memo", models.TextField(null=True, verbose_name="메모")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainer.trainer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "delivery_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="배송 정보 고유 ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="배송지 주소"),
                ),
                (
                    "address_detail",
                    models.CharField(max_length=50, verbose_name="상세 주소"),
                ),
                (
                    "doorlock",
                    models.IntegerField(null=True, verbose_name="공동 현관 번호"),
                ),
                (
                    "doorlock_type",
                    models.IntegerField(
                        choices=[
                            (0, "비밀번호"),
                            (1, "경비실 호출"),
                            (2, "자유출입가능"),
                        ],
                        verbose_name="공동 현관 출입 방법",
                    ),
                ),
                (
                    "message",
                    models.IntegerField(
                        choices=[(0, "문 앞에 놔주세요"), (1, "직접 입력")],
                        null=True,
                        verbose_name="배송 메시지",
                    ),
                ),
                (
                    "message_detail",
                    models.CharField(
                        max_length=100, null=True, verbose_name="직접 입력 메시지"
                    ),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="수정일자"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Body_Data",
            fields=[
                (
                    "body_data_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="신체 정보 고유 ID",
                    ),
                ),
                (
                    "skeletal_muscle",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, null=True, verbose_name="활동량"
                    ),
                ),
                (
                    "body_fat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="체지방량",
                    ),
                ),
                (
                    "body_fat_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="체지방률",
                    ),
                ),
                (
                    "bmr",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="기초 대사량 (BMR)",
                    ),
                ),
                (
                    "tdee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="활동 대사량 (TDEE)",
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="체질량 지수 (BMI)",
                    ),
                ),
                (
                    "bmi_rank",
                    models.IntegerField(
                        choices=[
                            (0, "저체중"),
                            (1, "정상"),
                            (2, "과체중"),
                            (3, "1단계 비만"),
                            (4, "2단계 비만"),
                            (5, "3단계 비만 (고도)"),
                        ],
                        null=True,
                        verbose_name="BMI 등급",
                    ),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="수정일자"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="client.client"
                    ),
                ),
            ],
        ),
    ]
