# Generated by Django 4.2.14 on 2024-08-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="body_data",
            table="body_data",
        ),
        migrations.AlterModelTable(
            name="client",
            table="client",
        ),
        migrations.AlterModelTable(
            name="delivery",
            table="delivery",
        ),
    ]
