# Generated by Django 4.2.14 on 2024-08-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_client_is_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="height",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="신장"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="체중"
            ),
        ),
    ]
