# Generated by Django 4.2.14 on 2024-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_client_height_alter_client_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.PositiveBigIntegerField(verbose_name="연락처"),
        ),
    ]
