# Generated by Django 4.2.13 on 2024-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_alter_client_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="weight",
        ),
        migrations.AddField(
            model_name="body_data",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="체중"
            ),
        ),
    ]
