# Generated by Django 4.2.13 on 2024-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_alter_body_data_skeletal_muscle"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="subscribe_dt",
            field=models.DateTimeField(auto_now=True, verbose_name="구독일자"),
        ),
    ]
