# Generated by Django 4.2.13 on 2024-09-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_client_subscribe_dt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="height",
        ),
        migrations.AddField(
            model_name="body_data",
            name="height",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="신장"
            ),
        ),
    ]
