# Generated by Django 4.2.13 on 2024-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_remove_client_height_body_data_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.CharField(max_length=15, verbose_name="연락처"),
        ),
    ]
