# Generated by Django 4.2.13 on 2024-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_alter_client_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="address",
            field=models.CharField(
                max_length=200, null=True, verbose_name="배송지 주소"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="address_detail",
            field=models.CharField(max_length=50, null=True, verbose_name="상세 주소"),
        ),
    ]
