# Generated by Django 4.2.13 on 2024-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_alter_delivery_address_alter_delivery_address_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="message",
            field=models.IntegerField(
                choices=[
                    (0, "배송메시지를 선택해주세요."),
                    (1, "문 앞에 놔주세요"),
                    (2, "직접 입력"),
                ],
                null=True,
                verbose_name="배송 메시지",
            ),
        ),
    ]
