# Generated by Django 4.2.13 on 2024-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0012_alter_delivery_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_subscribed",
            field=models.IntegerField(
                choices=[
                    (0, "구독 안 함"),
                    (1, "구독 중"),
                    (2, "구독 알림"),
                    (3, "구독 중단"),
                ],
                default=0,
                verbose_name="구독 상태",
            ),
        ),
    ]
