# Generated by Django 4.2.14 on 2024-08-18 20:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "gym_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="헬스장 고유 ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="헬스장 이름")),
                (
                    "address",
                    models.CharField(max_length=200, verbose_name="헬스장 주소"),
                ),
                (
                    "place_id",
                    models.IntegerField(null=True, verbose_name="카카오맵 주소 ID"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "trainer_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="트레이너 고유 ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=70, null=True, verbose_name="로그인 ID"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=100, null=True, verbose_name="로그인 PW"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                (
                    "sns_id",
                    models.CharField(
                        max_length=100, null=True, verbose_name="SNS 로그인 ID"
                    ),
                ),
                (
                    "sns_type",
                    models.IntegerField(
                        choices=[(0, "네이버"), (1, "구글"), (2, "카카오")],
                        null=True,
                        verbose_name="SNS 종류",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="승인 유무"),
                ),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trainer.gym"
                    ),
                ),
            ],
        ),
    ]
