# Generated by Django 4.2.14 on 2024-08-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gym",
            table="gym",
        ),
        migrations.AlterModelTable(
            name="trainer",
            table="trainer",
        ),
    ]
