# Generated by Django 4.2.14 on 2024-08-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0002_alter_gym_table_alter_trainer_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="username",
            field=models.CharField(
                max_length=70, null=True, unique=True, verbose_name="로그인 ID"
            ),
        ),
    ]
