# Generated by Django 4.2.14 on 2024-08-21 03:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0003_trainer_last_login_alter_trainer_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="trainer",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
