# Generated by Django 4.2.13 on 2024-08-24 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0006_trainer_is_subscribed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile_Image",
            fields=[
                (
                    "profile_image_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="프로필 사진 고유 ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="profile_image")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainer.trainer",
                    ),
                ),
            ],
            options={
                "db_table": "profile_image",
            },
        ),
    ]
