# Generated by Django 4.2.13 on 2024-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0007_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="관리자 유무"),
        ),
    ]
