# Generated by Django 4.2.14 on 2024-08-19 01:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseInfo",
            fields=[
                (
                    "baseinfo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="베이스 유틸 상세 고유 ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 요리 유무"),
                ),
                (
                    "base_util",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.base_util",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.meal"
                    ),
                ),
            ],
            options={
                "db_table": "baseinfo",
            },
        ),
        migrations.CreateModel(
            name="FlavorInfo",
            fields=[
                (
                    "flavorinfo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="소스 유틸 상세 고유 ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 요리 유무"),
                ),
                (
                    "flavor_util",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.flavor_util",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.meal"
                    ),
                ),
            ],
            options={
                "db_table": "flavorinfo_id",
            },
        ),
        migrations.CreateModel(
            name="ProInfo",
            fields=[
                (
                    "proinfo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="단백 유틸 상세 고유 ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 요리 유무"),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.meal"
                    ),
                ),
                (
                    "pro_util",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.pro_util"
                    ),
                ),
            ],
            options={
                "db_table": "proinfo",
            },
        ),
        migrations.CreateModel(
            name="VegInfo",
            fields=[
                (
                    "veginfo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="채소 유틸 상세 고유 ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "월요일"),
                            (1, "화요일"),
                            (2, "수요일"),
                            (3, "목요일"),
                            (4, "금요일"),
                            (5, "토요일"),
                        ],
                        verbose_name="요일",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 요리 유무"),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.meal"
                    ),
                ),
                (
                    "veg_util",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.veg_util"
                    ),
                ),
            ],
            options={
                "db_table": "veginfo",
            },
        ),
        migrations.DeleteModel(
            name="Meal_Detail",
        ),
    ]
