# Generated by Django 4.2.14 on 2024-08-22 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_base_util_table_alter_baseinfo_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu_Image",
            fields=[
                (
                    "menu_image_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="메뉴 사진 고유 ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="menu_image")),
                (
                    "create_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "update_dt",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
            ],
            options={
                "db_table": "menu_image",
            },
        ),
        migrations.RemoveField(
            model_name="order_detail",
            name="order",
        ),
        migrations.CreateModel(
            name="Order_Week",
            fields=[
                (
                    "order_week_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="주문한 주 고유 ID",
                    ),
                ),
                ("week", models.IntegerField(default=0, verbose_name="몇 번째 주")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
            options={
                "db_table": "order_week",
            },
        ),
        migrations.AddField(
            model_name="order_detail",
            name="order_week",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="order.order_week",
            ),
            preserve_default=False,
        ),
    ]
