# Generated by Django 4.2.13 on 2024-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_add_veg_add_pro_add_flavor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu_Image",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="총 결제 금액"),
        ),
    ]
