# Generated by Django 4.2.13 on 2024-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_rename_amount_order_total_amount_order_added_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="added_amount",
        ),
        migrations.AddField(
            model_name="order_detail",
            name="added_amount",
            field=models.IntegerField(default=0, verbose_name="추가 금액"),
        ),
    ]
