# Generated by Django 4.2.13 on 2024-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_remove_order_added_amount_order_detail_added_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_detail",
            old_name="added_amount",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="order",
            name="added_amount",
            field=models.IntegerField(default=0, verbose_name="추가 금액"),
        ),
    ]
