# Generated by Django 4.2.13 on 2024-10-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_remove_payment_billing_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_week",
            name="meal_group",
            field=models.CharField(
                max_length=50, null=True, verbose_name="식단 유형명"
            ),
        ),
    ]
