# Generated by Django 4.2.13 on 2024-10-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0013_order_week_meal_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="is_pickup",
            new_name="is_delivery",
        ),
    ]
